### ISSUE TITLE
PACKAGE keyword is not colored

### ISSUE THREAD

**Issue by xtof1** [sekineh/vscode-flexlm-license-file#4]
PACKAGE keyword shall be colored like FEATURE

**Comment by n8felton** [comment]
This should be resolved with #2, just waiting for a new release to be published to the Marketplace

**Comment by sekineh** [comment]
Oh, hopefully I’ll release it next week.
Thanks for using this extension!

**Comment by sekineh** [comment]
Today I published `v0.2.0` which include #2 change set to the Marketplace.

Enjoy!
